name: varbase
recipe: drupal8
config:
  webroot: docroot
  php: '7.3'
  drush: ^9
services:
  appserver:
    scanner: false
    build:
      - "composer global require drupal/coder dealerdirect/phpcodesniffer-composer-installer mglaman/drupal-check"
      - 'export PATH="/var/www/.composer/vendor/bin"'
      - "wget https://asm89.github.io/d/twig-lint.phar -P /var/www"
  node:
    type: node
    build:
      - "npm install jshint csslint -g"
tooling:
  phpcs:
    service: appserver
    cmd: "phpcs"
    options:
    description: Run phpcs for given folder or file.
  drupal-check:
    service: appserver
    cmd: "drupal-check"
    options:
    description: Run drupal-check for given folder or file.
  twig-lint:
    service: appserver
    cmd: "php /var/www/twig-lint.phar"
    options:
    description: Run twig-lint for given folder or file.
  jshint:
    service: node
    cmd: "jshint"
    options:
    description: Run jshint for given folder or file.
  csslint:
    service: node
    cmd: "csslint"
    options:
    description: Run csslint for given folder or file.
